services:
  frontend:
    image: oven/bun:1.1.13
    container_name: ema-frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -c "bun install && bun run dev --host"

  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: ema-frontend-test
    volumes:
      - .:/app