# Dockerfile.test

FROM node:20-alpine

WORKDIR /app

COPY . .

# Instala solo lo necesario para pruebas
RUN npm install --legacy-peer-deps \
  vitest \
  @testing-library/react \
  jsdom \
  @vitejs/plugin-react

CMD ["npx", "vitest", "run"]