export { default as Home } from './Home';
export { default as About } from './About';
export { default as Profile } from './Profile';
export { default as Settings } from './Settings';
export { default as Contact } from './Contact';
export { default as Register } from './Register';
export { default as StudentDashboard } from './student/StudentDashboard';
export { default as StudentCalendar } from './student/StudentCalendar';
export { default as StudentHistoryPayments } from './student/StudentHistoryPayments';
